export type CurriculumCourse = {
  codigo: string;
  nombre: string;
  ciclo: number | null;
  creditos: number;
  horasTeoria: number;
  horasPractica: number;
  modalidad: string;
  prerrequisitos: string[];
  tipoCurso?: string | null;
  areaCurricular?: string | null;
  aliases?: string[];
};

export function normalizeCourseName(value: string) {
  return String(value ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replace(/[^a-z0-9\s]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

const OBLIGATORIO = "Obligatorio";
const ELECTIVO = "Electivo";

export const curriculumCourses: CurriculumCourse[] = [
  // CICLO 1
  {
    codigo: "09066801054",
    nombre: "MATEMÁTICA DISCRETA",
    ciclo: 1,
    creditos: 5,
    horasTeoria: 4,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: [],
  },
  {
    codigo: "09066301043",
    nombre: "GEOMETRÍA ANALÍTICA",
    ciclo: 1,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: [],
  },
  {
    codigo: "09000301033",
    nombre: "FILOSOFÍA",
    ciclo: 1,
    creditos: 3,
    horasTeoria: 3,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: [],
  },
  {
    codigo: "09990601021",
    nombre: "CIUDADANÍA INTERCULTURAL",
    ciclo: 1,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: [],
  },
  {
    codigo: "09230001021",
    nombre: "INTRODUCCIÓN A SISTEMAS DE INFORMACIÓN",
    ciclo: 1,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: [],
  },
  {
    codigo: "09000201025",
    nombre: "LENGUAJE",
    ciclo: 1,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: [],
  },
  {
    codigo: "09071001025",
    nombre: "MÉTODOS DE ESTUDIO",
    ciclo: 1,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: [],
  },
  {
    codigo: "TR000501010",
    nombre: "ACTIVIDADES I",
    ciclo: 1,
    creditos: 1,
    horasTeoria: 0,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: [],
  },
  {
    codigo: "TR000101010",
    nombre: "INGLÉS I",
    ciclo: 1,
    creditos: 1,
    horasTeoria: 0,
    horasPractica: 2,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: [],
  },

  // CICLO 2
  {
    codigo: "09036602053",
    nombre: "ÁLGEBRA LINEAL",
    ciclo: 2,
    creditos: 5,
    horasTeoria: 4,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: [],
    aliases: ["ALGEBRA LINEAL"],
  },
  {
    codigo: "09065502053",
    nombre: "CÁLCULO I",
    ciclo: 2,
    creditos: 5,
    horasTeoria: 4,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: ["MATEMÁTICA DISCRETA", "GEOMETRÍA ANALÍTICA"],
    aliases: ["CALCULO I"],
  },
  {
    codigo: "09111402053",
    nombre: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    ciclo: 2,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["MATEMÁTICA DISCRETA"],
  },
  {
    codigo: "09066502033",
    nombre: "FUNDAMENTOS DE DISEÑO WEB",
    ciclo: 2,
    creditos: 3,
    horasTeoria: 2,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["INTRODUCCIÓN A SISTEMAS DE INFORMACIÓN"],
    aliases: ["FUNDAMENTOS DE DISENO WEB"],
  },
  {
    codigo: "09127402032",
    nombre: "INTRODUCCIÓN A LA ECONOMÍA",
    ciclo: 2,
    creditos: 3,
    horasTeoria: 2,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: ["CIUDADANÍA INTERCULTURAL"],
    aliases: ["INTRODUCCION A LA ECONOMIA"],
  },
  {
    codigo: "TR000602010",
    nombre: "ACTIVIDADES II",
    ciclo: 2,
    creditos: 1,
    horasTeoria: 0,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: ["ACTIVIDADES I"],
  },
  {
    codigo: "TR000202010",
    nombre: "INGLÉS II",
    ciclo: 2,
    creditos: 1,
    horasTeoria: 0,
    horasPractica: 2,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: ["INGLÉS I"],
    aliases: ["INGLES II"],
  },

  // CICLO 3
  {
    codigo: "09005303052",
    nombre: "ALGORITMOS Y ESTRUCTURA DE DATOS I",
    ciclo: 3,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["INTRODUCCIÓN A LA PROGRAMACIÓN"],
  },
  {
    codigo: "09005603055",
    nombre: "FÍSICA I",
    ciclo: 3,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: ["ÁLGEBRA LINEAL", "CÁLCULO I"],
    aliases: ["FISICA I"],
  },
  {
    codigo: "09111503052",
    nombre: "TECNOLOGÍA DE INFORMACIÓN I",
    ciclo: 3,
    creditos: 5,
    horasTeoria: 4,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["INTRODUCCIÓN A LA PROGRAMACIÓN"],
    aliases: ["TECNOLOGIA DE INFORMACION I"],
  },
  {
    codigo: "09005403044",
    nombre: "ESTADÍSTICA Y PROBABILIDADES I",
    ciclo: 3,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: ["CÁLCULO I"],
    aliases: ["ESTADISTICA Y PROBABILIDADES I"],
  },
  {
    codigo: "09127603032",
    nombre: "SISTEMAS DE INFORMACIÓN",
    ciclo: 3,
    creditos: 3,
    horasTeoria: 2,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["FUNDAMENTOS DE DISEÑO WEB"],
    aliases: ["SISTEMAS DE INFORMACION"],
  },

  // CICLO 4
  {
    codigo: "09006904052",
    nombre: "ALGORITMOS Y ESTRUCTURA DE DATOS II",
    ciclo: 4,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["ALGORITMOS Y ESTRUCTURA DE DATOS I"],
  },
  {
    codigo: "09007404054",
    nombre: "FÍSICA II",
    ciclo: 4,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: ["FÍSICA I"],
    aliases: ["FISICA II"],
  },
  {
    codigo: "09006004042",
    nombre: "ESTADÍSTICA Y PROBABILIDADES II",
    ciclo: 4,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: ["ESTADÍSTICA Y PROBABILIDADES I"],
    aliases: ["ESTADISTICA Y PROBABILIDADES II"],
  },
  {
    codigo: "09007704043",
    nombre: "MICROECONOMÍA",
    ciclo: 4,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: ["CÁLCULO I", "INTRODUCCIÓN A LA ECONOMÍA"],
    aliases: ["MICROECONOMIA"],
  },
  {
    codigo: "09114904042",
    nombre: "TECNOLOGÍA DE INFORMACIÓN II",
    ciclo: 4,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["TECNOLOGÍA DE INFORMACIÓN I"],
    aliases: ["TECNOLOGIA DE INFORMACION II"],
  },

  // CICLO 5
  {
    codigo: "09093205053",
    nombre: "GESTIÓN DE PROCESOS",
    ciclo: 5,
    creditos: 5,
    horasTeoria: 4,
    horasPractica: 2,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: [
      "ALGORITMOS Y ESTRUCTURA DE DATOS II",
      "SISTEMAS DE INFORMACIÓN",
    ],
    aliases: ["GESTION DE PROCESOS"],
  },
  {
    codigo: "09008905052",
    nombre: "TEORÍA Y DISEÑO DE BASES DE DATOS",
    ciclo: 5,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["ALGORITMOS Y ESTRUCTURA DE DATOS II"],
    aliases: ["TEORIA Y DISENO DE BASES DE DATOS"],
  },
  {
    codigo: "09012205048",
    nombre: "CONTABILIDAD GENERAL",
    ciclo: 5,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: ["80 CRÉDITOS APROBADOS"],
    aliases: ["80 CREDITOS APROBADOS"],
  },
  {
    codigo: "09009005046",
    nombre: "INGENIERÍA ADMINISTRATIVA",
    ciclo: 5,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: ["MICROECONOMÍA"],
    aliases: ["INGENIERIA ADMINISTRATIVA"],
  },
  {
    codigo: "09140005041",
    nombre: "SISTEMAS OPERATIVOS Y PLATAFORMAS",
    ciclo: 5,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Tecnologías de Información",
    prerrequisitos: ["TECNOLOGÍA DE INFORMACIÓN II"],
    aliases: ["SISTEMAS OPERATIVOS Y PLATAFORMAS"],
  },

  // CICLO 6
  {
    codigo: "09011906052",
    nombre: "INGENIERÍA DE SOFTWARE I",
    ciclo: 6,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Ingeniería de Software",
    prerrequisitos: [
      "GESTIÓN DE PROCESOS",
      "SISTEMAS OPERATIVOS Y PLATAFORMAS",
    ],
    aliases: ["INGENIERIA DE SOFTWARE I"],
  },
  {
    codigo: "09067106052",
    nombre: "PROGRAMACIÓN I",
    ciclo: 6,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Ingeniería de Software",
    prerrequisitos: ["TEORÍA Y DISEÑO DE BASES DE DATOS"],
    aliases: ["PROGRAMACION I"],
  },
  {
    codigo: "09013106044",
    nombre: "INGENIERÍA DE COSTOS",
    ciclo: 6,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: ["CONTABILIDAD GENERAL"],
    aliases: ["INGENIERIA DE COSTOS"],
  },
  {
    codigo: "09008506045",
    nombre: "INVESTIGACIÓN OPERATIVA I",
    ciclo: 6,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Matemática y Ciencias",
    prerrequisitos: [
      "ESTADÍSTICA Y PROBABILIDADES II",
      "INTRODUCCIÓN A SISTEMAS DE INFORMACIÓN",
    ],
    aliases: ["INVESTIGACION OPERATIVA I"],
  },
  {
    codigo: "09008806042",
    nombre: "TEORÍA GENERAL DE SISTEMAS",
    ciclo: 6,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["INGENIERÍA ADMINISTRATIVA"],
    aliases: ["TEORIA GENERAL DE SISTEMAS"],
  },

  // CICLO 7
  {
    codigo: "09013707052",
    nombre: "INGENIERÍA DE SOFTWARE II",
    ciclo: 7,
    creditos: 5,
    horasTeoria: 3,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Ingeniería de Software",
    prerrequisitos: ["INGENIERÍA DE SOFTWARE I"],
    aliases: ["INGENIERIA DE SOFTWARE II"],
  },
  {
    codigo: "09014507044",
    nombre: "GESTIÓN FINANCIERA",
    ciclo: 7,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: ["INGENIERÍA DE COSTOS"],
    aliases: ["GESTION FINANCIERA"],
  },
  {
    codigo: "09140707041",
    nombre: "INTELIGENCIA ARTIFICIAL",
    ciclo: 7,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["PROGRAMACIÓN I"],
  },
  {
    codigo: "09140507021",
    nombre: "ARQUITECTURA DE SOFTWARE PARA SISTEMAS DE INFORMACIÓN",
    ciclo: 7,
    creditos: 2,
    horasTeoria: 0,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Ingeniería de Software",
    prerrequisitos: ["INGENIERÍA DE SOFTWARE I"],
    aliases: ["ARQUITECTURA DE SOFTWARE PARA SISTEMAS DE INFORMACION"],
  },
  {
    codigo: "09990707013",
    nombre: "DISCAPACIDAD E INCLUSIÓN",
    ciclo: 7,
    creditos: 1,
    horasTeoria: 0,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: ["133 CRÉDITOS APROBADOS"],
    aliases: ["DISCAPACIDAD E INCLUSION"],
  },
  {
    codigo: "ELECT-C7-01",
    nombre: "ELECTIVAS",
    ciclo: 7,
    creditos: 6,
    horasTeoria: 2,
    horasPractica: 8,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivos",
    prerrequisitos: [],
  },

  // CICLO 8
  {
    codigo: "09112108051",
    nombre: "TALLER DE PROYECTOS",
    ciclo: 8,
    creditos: 5,
    horasTeoria: 0,
    horasPractica: 10,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Ingeniería de Software",
    prerrequisitos: ["INGENIERÍA DE SOFTWARE II", "INTELIGENCIA ARTIFICIAL"],
    aliases: ["TALLER DE PROYECTO", "TALLER PROYECTO", "TALLER PROYECTOS"],
  },
  {
    codigo: "09128808042",
    nombre: "ARQUITECTURA EMPRESARIAL",
    ciclo: 8,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: [
      "TEORÍA GENERAL DE SISTEMAS",
      "ARQUITECTURA DE SOFTWARE PARA SISTEMAS DE INFORMACIÓN",
    ],
    aliases: ["ARQUITECTURA EMPRESARIAL"],
  },
  {
    codigo: "09072108042",
    nombre: "DISEÑO E IMPLEMENTACIÓN DE SISTEMAS",
    ciclo: 8,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Ingeniería de Software",
    prerrequisitos: ["INGENIERÍA DE SOFTWARE II"],
    aliases: ["DISEÑO E IMPLEMENTACION DE SISTEMAS"],
  },
  {
    codigo: "09054808043",
    nombre: "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS",
    ciclo: 8,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: ["GESTIÓN FINANCIERA"],
    aliases: ["FORMULACION Y EVALUACION DE PROYECTOS"],
  },
  {
    codigo: "09066408042",
    nombre: "GESTIÓN DE RECURSOS DE TECNOLOGÍAS DE INFORMACIÓN",
    ciclo: 8,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Tecnologías de Información",
    prerrequisitos: ["INGENIERÍA DE SOFTWARE II"],
    aliases: ["GESTION DE RECURSOS DE TECNOLOGIAS DE INFORMACION"],
  },
  {
    codigo: "09140108020",
    nombre: "INVESTIGACIÓN EN SISTEMAS DE INFORMACIÓN",
    ciclo: 8,
    creditos: 2,
    horasTeoria: 2,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Investigación",
    prerrequisitos: ["155 CRÉDITOS APROBADOS"],
    aliases: ["INVESTIGACION EN SISTEMAS DE INFORMACION"],
  },

  // CICLO 9
  {
    codigo: "09093409043",
    nombre: "INTELIGENCIA DE NEGOCIOS",
    ciclo: 9,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["ARQUITECTURA EMPRESARIAL"],
  },
  {
    codigo: "09067009042",
    nombre: "PLANEAMIENTO ESTRATÉGICO DE TECNOLOGÍAS DE INFORMACIÓN",
    ciclo: 9,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Tecnologías de Información",
    prerrequisitos: ["GESTIÓN DE RECURSOS DE TECNOLOGÍAS DE INFORMACIÓN"],
    aliases: ["PLANEAMIENTO ESTRATEGICO DE TECNOLOGIAS DE INFORMACION"],
  },
  {
    codigo: "09067309042",
    nombre: "PROYECTO FINAL DE INGENIERÍA DE COMPUTACIÓN Y SISTEMAS (*)",
    ciclo: 9,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Investigación",
    prerrequisitos: [
      "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS",
      "TALLER DE PROYECTOS",
      "INVESTIGACIÓN EN SISTEMAS DE INFORMACIÓN",
    ],
    aliases: [
      "PROYECTO FINAL DE INGENIERIA DE COMPUTACION Y SISTEMAS",
      "PROYECTO FINAL DE INGENIERIA DE COMPUTACION Y SISTEMAS (*)",
    ],
  },
  {
    codigo: "09067909042",
    nombre: "SEGURIDAD Y AUDITORÍA DE SISTEMAS DE INFORMACIÓN",
    ciclo: 9,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Tecnologías de Información",
    prerrequisitos: ["DISEÑO E IMPLEMENTACIÓN DE SISTEMAS"],
    aliases: ["SEGURIDAD Y AUDITORIA DE SISTEMAS DE INFORMACION"],
  },
  {
    codigo: "09066709022",
    nombre: "LIDERAZGO Y ORATORIA",
    ciclo: 9,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: ["100 CRÉDITOS APROBADOS"],
  },
  {
    codigo: "ELECT-C9-01",
    nombre: "ELECTIVA I",
    ciclo: 9,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivos",
    prerrequisitos: [],
  },
  {
    codigo: "ELECT-C9-02",
    nombre: "ELECTIVA II",
    ciclo: 9,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivos",
    prerrequisitos: [],
  },

  // CICLO 10
  {
    codigo: "09134910042",
    nombre: "MARKETING DIGITAL",
    ciclo: 10,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Gestión de la Computación",
    prerrequisitos: ["FORMULACIÓN Y EVALUACIÓN DE PROYECTOS"],
  },
  {
    codigo: "09990810041",
    nombre: "TRABAJO DE INVESTIGACIÓN (*)",
    ciclo: 10,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "VIRTUAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Investigación",
    prerrequisitos: [
      "PROYECTO FINAL DE INGENIERÍA DE COMPUTACIÓN Y SISTEMAS (*)",
    ],
    aliases: ["TRABAJO DE INVESTIGACION (*)", "TRABAJO DE INVESTIGACION"],
  },
  {
    codigo: "09147210030",
    nombre: "MANAGEMENT INFORMATION SYSTEMS",
    ciclo: 10,
    creditos: 3,
    horasTeoria: 3,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Sistemas de Información",
    prerrequisitos: ["196 CRÉDITOS APROBADOS"],
  },
  {
    codigo: "09147310020",
    nombre: "CIBERSEGURIDAD",
    ciclo: 10,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Tecnologías de Información",
    prerrequisitos: [
      "PLANEAMIENTO ESTRATÉGICO DE TECNOLOGÍAS DE INFORMACIÓN",
      "SEGURIDAD Y AUDITORÍA DE SISTEMAS DE INFORMACIÓN",
    ],
  },
  {
    codigo: "09003410025",
    nombre: "ÉTICA Y MORAL",
    ciclo: 10,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: OBLIGATORIO,
    areaCurricular: "Estudios Generales",
    prerrequisitos: ["170 CRÉDITOS APROBADOS"],
    aliases: ["ETICA Y MORAL"],
  },
  {
    codigo: "ELECT-C10-01",
    nombre: "ELECTIVAS",
    ciclo: 10,
    creditos: 7,
    horasTeoria: 6,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivos",
    prerrequisitos: [],
  },

  // ELECTIVAS DE ESPECIALIDAD - SISTEMAS DE INFORMACIÓN
  {
    codigo: "090861E1042",
    nombre: "ADMINISTRACIÓN DE BASE DE DATOS",
    ciclo: null,
    creditos: 4,
    horasTeoria: 2,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Sistemas de Información",
    prerrequisitos: ["TEORÍA Y DISEÑO DE BASES DE DATOS"],
    aliases: ["ADMINISTRACION DE BASE DE DATOS"],
  },
  {
    codigo: "090205E1041",
    nombre: "COMERCIO ELECTRÓNICO",
    ciclo: null,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Sistemas de Información",
    prerrequisitos: ["134 CRÉDITOS APROBADOS"],
    aliases: ["COMERCIO ELECTRONICO"],
  },
  {
    codigo: "090933E1041",
    nombre: "GESTIÓN DEL CONOCIMIENTO",
    ciclo: null,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Sistemas de Información",
    prerrequisitos: ["150 CRÉDITOS APROBADOS"],
    aliases: ["GESTION DEL CONOCIMIENTO"],
  },
  {
    codigo: "091119E1043",
    nombre: "SISTEMAS INTEGRADOS DE GESTIÓN ERP",
    ciclo: null,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Sistemas de Información",
    prerrequisitos: ["GESTIÓN DE RECURSOS DE TECNOLOGÍAS DE INFORMACIÓN"],
    aliases: ["SISTEMAS INTEGRADOS DE GESTION ERP"],
  },
  {
    codigo: "090608E1042",
    nombre: "TALLER DE CREATIVIDAD EMPRESARIAL",
    ciclo: null,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Sistemas de Información",
    prerrequisitos: ["TALLER DE PROYECTOS"],
  },
  {
    codigo: "091406E1031",
    nombre: "BIG DATA",
    ciclo: null,
    creditos: 3,
    horasTeoria: 2,
    horasPractica: 2,
    modalidad: "VIRTUAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Sistemas de Información",
    prerrequisitos: ["150 CRÉDITOS APROBADOS"],
  },
  {
    codigo: "091474E1030",
    nombre: "DATA SCIENCE",
    ciclo: null,
    creditos: 3,
    horasTeoria: 3,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Sistemas de Información",
    prerrequisitos: ["155 CRÉDITOS APROBADOS"],
  },
  {
    codigo: "092301E7021",
    nombre: "ROTACIÓN EXTERNA SISTEMAS DE INFORMACIÓN",
    ciclo: null,
    creditos: 2,
    horasTeoria: 0,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Sistemas de Información",
    prerrequisitos: [
      "INVESTIGACIÓN OPERATIVA I",
      "TEORÍA GENERAL DE SISTEMAS",
      "INGENIERÍA DE SOFTWARE I",
      "INGENIERÍA DE COSTOS",
      "PROGRAMACIÓN I",
    ],
    aliases: ["ROTACION EXTERNA SISTEMAS DE INFORMACION"],
  },

  // ELECTIVAS DE ESPECIALIDAD - TECNOLOGÍAS DE INFORMACIÓN
  {
    codigo: "090675E2041",
    nombre: "REDES Y CONECTIVIDAD I (CCNA I CISCO)",
    ciclo: null,
    creditos: 4,
    horasTeoria: 2,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Tecnologías de Información",
    prerrequisitos: ["SISTEMAS OPERATIVOS Y PLATAFORMAS"],
  },
  {
    codigo: "090676E2041",
    nombre: "REDES Y CONECTIVIDAD II (CCNA II CISCO)",
    ciclo: null,
    creditos: 4,
    horasTeoria: 2,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Tecnologías de Información",
    prerrequisitos: ["REDES Y CONECTIVIDAD I (CCNA I CISCO)"],
  },
  {
    codigo: "090677E2041",
    nombre: "REDES Y CONECTIVIDAD III (CCNA III CISCO)",
    ciclo: null,
    creditos: 4,
    horasTeoria: 2,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Tecnologías de Información",
    prerrequisitos: ["REDES Y CONECTIVIDAD II (CCNA II CISCO)"],
  },
  {
    codigo: "090862E2041",
    nombre: "SEGURIDAD INFORMÁTICA",
    ciclo: null,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Tecnologías de Información",
    prerrequisitos: ["SEGURIDAD Y AUDITORÍA DE SISTEMAS DE INFORMACIÓN"],
    aliases: ["SEGURIDAD INFORMATICA"],
  },

  // ELECTIVAS DE ESPECIALIDAD - INGENIERÍA DE SOFTWARE
  {
    codigo: "090658E3041",
    nombre: "CALIDAD DE SOFTWARE",
    ciclo: null,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Ingeniería de Software",
    prerrequisitos: ["PRUEBAS DE SOFTWARE"],
  },
  {
    codigo: "090672E3041",
    nombre: "PROGRAMACIÓN II",
    ciclo: null,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Ingeniería de Software",
    prerrequisitos: ["PROGRAMACIÓN I"],
    aliases: ["PROGRAMACION II"],
  },
  {
    codigo: "091124E3041",
    nombre: "PRUEBAS DE SOFTWARE",
    ciclo: null,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas de Ingeniería de Software",
    prerrequisitos: ["INGENIERÍA DE SOFTWARE II"],
  },

  // ELECTIVAS LIBRES
  {
    codigo: "091126E4041",
    nombre: "DESARROLLO DE JUEGOS",
    ciclo: null,
    creditos: 4,
    horasTeoria: 4,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas Libres",
    prerrequisitos: ["INGENIERÍA DE SOFTWARE II"],
  },
  {
    codigo: "09085209041",
    nombre: "GESTIÓN DE PROYECTOS - PMI",
    ciclo: null,
    creditos: 4,
    horasTeoria: 2,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas Libres",
    prerrequisitos: ["FORMULACIÓN Y EVALUACIÓN DE PROYECTOS"],
  },
  {
    codigo: "09061700040",
    nombre: "GESTIÓN ESTRATÉGICA",
    ciclo: null,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas Libres",
    prerrequisitos: ["120 CRÉDITOS APROBADOS"],
  },
  {
    codigo: "09011607043",
    nombre: "INVESTIGACIÓN OPERATIVA II",
    ciclo: null,
    creditos: 4,
    horasTeoria: 3,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas Libres",
    prerrequisitos: ["INVESTIGACIÓN OPERATIVA I"],
  },
  {
    codigo: "092302E9020",
    nombre: "FUNDAMENTOS DE EMPRENDIMIENTO",
    ciclo: null,
    creditos: 3,
    horasTeoria: 2,
    horasPractica: 2,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas Libres",
    prerrequisitos: ["152 CRÉDITOS APROBADOS"],
  },
  {
    codigo: "090147E4021",
    nombre: "COMPORTAMIENTO ORGANIZACIONAL",
    ciclo: null,
    creditos: 2,
    horasTeoria: 2,
    horasPractica: 0,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas Libres",
    prerrequisitos: ["INGENIERÍA ADMINISTRATIVA"],
  },
  {
    codigo: "09086300021",
    nombre: "GESTIÓN DE LA INNOVACIÓN",
    ciclo: null,
    creditos: 2,
    horasTeoria: 1,
    horasPractica: 2,
    modalidad: "VIRTUAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas Libres",
    prerrequisitos: ["FORMULACIÓN Y EVALUACIÓN DE PROYECTOS"],
  },
  {
    codigo: "092303E3020",
    nombre: "PROYECCIÓN SOCIAL",
    ciclo: null,
    creditos: 2,
    horasTeoria: 0,
    horasPractica: 4,
    modalidad: "PRESENCIAL",
    tipoCurso: ELECTIVO,
    areaCurricular: "Electivas Libres",
    prerrequisitos: [],
  },
];

export function getCourseComparableNames(course: CurriculumCourse) {
  return [course.codigo, course.nombre, ...(course.aliases ?? [])]
    .map(normalizeCourseName)
    .filter(Boolean);
}

export function findCurriculumCourseByName(name: string) {
  const normalized = normalizeCourseName(name);

  return (
    curriculumCourses.find((course) =>
      getCourseComparableNames(course).includes(normalized),
    ) ?? null
  );
}

export function getCurriculumAnteriores(course: CurriculumCourse): string[] {
  return course.prerrequisitos.slice(-2);
}

export function getCurriculumPosteriores(course: CurriculumCourse): string[] {
  const currentNames = getCourseComparableNames(course);

  return curriculumCourses
    .filter((item) =>
      item.prerrequisitos.some((prerrequisito) =>
        currentNames.includes(normalizeCourseName(prerrequisito)),
      ),
    )
    .map((item) => item.nombre)
    .slice(0, 2);
}
