name: OWASP ZAP Security Scan

on:
  push:
    branches: [feature_swagger]
  pull_request:
    branches: [dev, main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Scan (API Definition)
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: https://raw.githubusercontent.com/TALLER-PROYECTOS-2026-I/SGA_BACKEND/refs/heads/feature_swagger/docs/swagger.yml
          format: "openapi"
          fail_action: false

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: /zap/wrk/report_html.html # La ruta donde ZAP guarda el reporte por defecto
